"""empty message

Revision ID: b05ea92a78d1
Revises: e6837b747de1
Create Date: 2021-09-25 13:10:23.743610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05ea92a78d1'
down_revision = 'e6837b747de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacao', sa.Column('conta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transacao', 'conta', ['conta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transacao', type_='foreignkey')
    op.drop_column('transacao', 'conta_id')
    # ### end Alembic commands ###
